// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pgrnk_pgrnk,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.212000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=120,HLS_SYN_DSP=0,HLS_SYN_FF=27827,HLS_SYN_LUT=20904,HLS_VERSION=2020_2}" *)

module pgrnk (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 64;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 64;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM3_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM3_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_USER_VALUE = 0;
parameter    C_M_AXI_GMEM3_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM3_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (64 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_GMEM3_WSTRB_WIDTH = (512 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_AWADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_AWID;
output  [7:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [C_M_AXI_GMEM3_AWUSER_WIDTH - 1:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_WDATA;
output  [C_M_AXI_GMEM3_WSTRB_WIDTH - 1:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_WID;
output  [C_M_AXI_GMEM3_WUSER_WIDTH - 1:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_ARADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_ARID;
output  [7:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [C_M_AXI_GMEM3_ARUSER_WIDTH - 1:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_RID;
input  [C_M_AXI_GMEM3_RUSER_WIDTH - 1:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_BID;
input  [C_M_AXI_GMEM3_BUSER_WIDTH - 1:0] m_axi_gmem3_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] num_verts;
wire   [63:0] num_edges;
wire   [63:0] vertices;
wire   [63:0] edges;
wire   [63:0] inputs;
wire   [63:0] outputs;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [511:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [511:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [511:0] gmem2_RDATA;
wire    gmem2_RLAST;
wire   [0:0] gmem2_RID;
wire   [0:0] gmem2_RUSER;
wire   [1:0] gmem2_RRESP;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    gmem3_AWREADY;
wire    gmem3_WREADY;
wire    gmem3_ARREADY;
wire    gmem3_RVALID;
wire   [511:0] gmem3_RDATA;
wire    gmem3_RLAST;
wire   [0:0] gmem3_RID;
wire   [0:0] gmem3_RUSER;
wire   [1:0] gmem3_RRESP;
wire    gmem3_BVALID;
wire   [1:0] gmem3_BRESP;
wire   [0:0] gmem3_BID;
wire   [0:0] gmem3_BUSER;
wire    pgrnk_entry3_U0_ap_start;
wire    pgrnk_entry3_U0_start_full_n;
wire    pgrnk_entry3_U0_ap_done;
wire    pgrnk_entry3_U0_ap_continue;
wire    pgrnk_entry3_U0_ap_idle;
wire    pgrnk_entry3_U0_ap_ready;
wire    pgrnk_entry3_U0_start_out;
wire    pgrnk_entry3_U0_start_write;
wire   [63:0] pgrnk_entry3_U0_num_verts_out_din;
wire    pgrnk_entry3_U0_num_verts_out_write;
wire   [63:0] pgrnk_entry3_U0_num_verts_out1_din;
wire    pgrnk_entry3_U0_num_verts_out1_write;
wire   [63:0] pgrnk_entry3_U0_num_edges_out_din;
wire    pgrnk_entry3_U0_num_edges_out_write;
wire   [63:0] pgrnk_entry3_U0_vertices_out_din;
wire    pgrnk_entry3_U0_vertices_out_write;
wire   [63:0] pgrnk_entry3_U0_edges_out_din;
wire    pgrnk_entry3_U0_edges_out_write;
wire   [63:0] pgrnk_entry3_U0_inputs_out_din;
wire    pgrnk_entry3_U0_inputs_out_write;
wire   [63:0] pgrnk_entry3_U0_outputs_out_din;
wire    pgrnk_entry3_U0_outputs_out_write;
wire    fetch_verts_U0_ap_start;
wire    fetch_verts_U0_ap_done;
wire    fetch_verts_U0_ap_continue;
wire    fetch_verts_U0_ap_idle;
wire    fetch_verts_U0_ap_ready;
wire    fetch_verts_U0_start_out;
wire    fetch_verts_U0_start_write;
wire    fetch_verts_U0_m_axi_gmem0_AWVALID;
wire   [63:0] fetch_verts_U0_m_axi_gmem0_AWADDR;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_AWID;
wire   [31:0] fetch_verts_U0_m_axi_gmem0_AWLEN;
wire   [2:0] fetch_verts_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] fetch_verts_U0_m_axi_gmem0_AWBURST;
wire   [1:0] fetch_verts_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] fetch_verts_U0_m_axi_gmem0_AWPROT;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_AWQOS;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_AWREGION;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_AWUSER;
wire    fetch_verts_U0_m_axi_gmem0_WVALID;
wire   [511:0] fetch_verts_U0_m_axi_gmem0_WDATA;
wire   [63:0] fetch_verts_U0_m_axi_gmem0_WSTRB;
wire    fetch_verts_U0_m_axi_gmem0_WLAST;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_WID;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_WUSER;
wire    fetch_verts_U0_m_axi_gmem0_ARVALID;
wire   [63:0] fetch_verts_U0_m_axi_gmem0_ARADDR;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_ARID;
wire   [31:0] fetch_verts_U0_m_axi_gmem0_ARLEN;
wire   [2:0] fetch_verts_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] fetch_verts_U0_m_axi_gmem0_ARBURST;
wire   [1:0] fetch_verts_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] fetch_verts_U0_m_axi_gmem0_ARPROT;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_ARQOS;
wire   [3:0] fetch_verts_U0_m_axi_gmem0_ARREGION;
wire   [0:0] fetch_verts_U0_m_axi_gmem0_ARUSER;
wire    fetch_verts_U0_m_axi_gmem0_RREADY;
wire    fetch_verts_U0_m_axi_gmem0_BREADY;
wire   [63:0] fetch_verts_U0_ie_counts_din;
wire    fetch_verts_U0_ie_counts_write;
wire   [63:0] fetch_verts_U0_oe_counts_din;
wire    fetch_verts_U0_oe_counts_write;
wire    fetch_verts_U0_num_verts_read;
wire    fetch_verts_U0_vertices_read;
wire    fetch_edges_U0_ap_start;
wire    fetch_edges_U0_ap_done;
wire    fetch_edges_U0_ap_continue;
wire    fetch_edges_U0_ap_idle;
wire    fetch_edges_U0_ap_ready;
wire    fetch_edges_U0_m_axi_gmem1_AWVALID;
wire   [63:0] fetch_edges_U0_m_axi_gmem1_AWADDR;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_AWID;
wire   [31:0] fetch_edges_U0_m_axi_gmem1_AWLEN;
wire   [2:0] fetch_edges_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] fetch_edges_U0_m_axi_gmem1_AWBURST;
wire   [1:0] fetch_edges_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] fetch_edges_U0_m_axi_gmem1_AWPROT;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_AWQOS;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_AWREGION;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_AWUSER;
wire    fetch_edges_U0_m_axi_gmem1_WVALID;
wire   [511:0] fetch_edges_U0_m_axi_gmem1_WDATA;
wire   [63:0] fetch_edges_U0_m_axi_gmem1_WSTRB;
wire    fetch_edges_U0_m_axi_gmem1_WLAST;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_WID;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_WUSER;
wire    fetch_edges_U0_m_axi_gmem1_ARVALID;
wire   [63:0] fetch_edges_U0_m_axi_gmem1_ARADDR;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_ARID;
wire   [31:0] fetch_edges_U0_m_axi_gmem1_ARLEN;
wire   [2:0] fetch_edges_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] fetch_edges_U0_m_axi_gmem1_ARBURST;
wire   [1:0] fetch_edges_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] fetch_edges_U0_m_axi_gmem1_ARPROT;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_ARQOS;
wire   [3:0] fetch_edges_U0_m_axi_gmem1_ARREGION;
wire   [0:0] fetch_edges_U0_m_axi_gmem1_ARUSER;
wire    fetch_edges_U0_m_axi_gmem1_RREADY;
wire    fetch_edges_U0_m_axi_gmem1_BREADY;
wire   [63:0] fetch_edges_U0_in_edges_din;
wire    fetch_edges_U0_in_edges_write;
wire    fetch_edges_U0_num_edges_read;
wire    fetch_edges_U0_edges_read;
wire   [63:0] fetch_edges_U0_num_edges_out_din;
wire    fetch_edges_U0_num_edges_out_write;
wire    fetch_weights_U0_ap_start;
wire    fetch_weights_U0_ap_done;
wire    fetch_weights_U0_ap_continue;
wire    fetch_weights_U0_ap_idle;
wire    fetch_weights_U0_ap_ready;
wire    fetch_weights_U0_m_axi_gmem2_AWVALID;
wire   [63:0] fetch_weights_U0_m_axi_gmem2_AWADDR;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_AWID;
wire   [31:0] fetch_weights_U0_m_axi_gmem2_AWLEN;
wire   [2:0] fetch_weights_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] fetch_weights_U0_m_axi_gmem2_AWBURST;
wire   [1:0] fetch_weights_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] fetch_weights_U0_m_axi_gmem2_AWPROT;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_AWQOS;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_AWREGION;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_AWUSER;
wire    fetch_weights_U0_m_axi_gmem2_WVALID;
wire   [511:0] fetch_weights_U0_m_axi_gmem2_WDATA;
wire   [63:0] fetch_weights_U0_m_axi_gmem2_WSTRB;
wire    fetch_weights_U0_m_axi_gmem2_WLAST;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_WID;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_WUSER;
wire    fetch_weights_U0_m_axi_gmem2_ARVALID;
wire   [63:0] fetch_weights_U0_m_axi_gmem2_ARADDR;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_ARID;
wire   [31:0] fetch_weights_U0_m_axi_gmem2_ARLEN;
wire   [2:0] fetch_weights_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] fetch_weights_U0_m_axi_gmem2_ARBURST;
wire   [1:0] fetch_weights_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] fetch_weights_U0_m_axi_gmem2_ARPROT;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_ARQOS;
wire   [3:0] fetch_weights_U0_m_axi_gmem2_ARREGION;
wire   [0:0] fetch_weights_U0_m_axi_gmem2_ARUSER;
wire    fetch_weights_U0_m_axi_gmem2_RREADY;
wire    fetch_weights_U0_m_axi_gmem2_BREADY;
wire    fetch_weights_U0_in_edges_read;
wire   [63:0] fetch_weights_U0_in_weights_din;
wire    fetch_weights_U0_in_weights_write;
wire    fetch_weights_U0_num_weights_read;
wire    fetch_weights_U0_weights_read;
wire    sum_weights_U0_ap_start;
wire    sum_weights_U0_ap_done;
wire    sum_weights_U0_ap_continue;
wire    sum_weights_U0_ap_idle;
wire    sum_weights_U0_ap_ready;
wire    sum_weights_U0_ie_counts_read;
wire    sum_weights_U0_in_weights_read;
wire   [63:0] sum_weights_U0_weights_din;
wire    sum_weights_U0_weights_write;
wire    sum_weights_U0_num_verts_read;
wire   [63:0] sum_weights_U0_num_verts_out_din;
wire    sum_weights_U0_num_verts_out_write;
wire    div_weights_U0_ap_start;
wire    div_weights_U0_ap_done;
wire    div_weights_U0_ap_continue;
wire    div_weights_U0_ap_idle;
wire    div_weights_U0_ap_ready;
wire    div_weights_U0_weights_read;
wire    div_weights_U0_oe_counts_read;
wire   [63:0] div_weights_U0_out_weights_din;
wire    div_weights_U0_out_weights_write;
wire    div_weights_U0_num_verts_read;
wire   [63:0] div_weights_U0_num_verts_out_din;
wire    div_weights_U0_num_verts_out_write;
wire    write_weights_U0_ap_start;
wire    write_weights_U0_ap_done;
wire    write_weights_U0_ap_continue;
wire    write_weights_U0_ap_idle;
wire    write_weights_U0_ap_ready;
wire    write_weights_U0_out_weights_read;
wire    write_weights_U0_m_axi_gmem3_AWVALID;
wire   [63:0] write_weights_U0_m_axi_gmem3_AWADDR;
wire   [0:0] write_weights_U0_m_axi_gmem3_AWID;
wire   [31:0] write_weights_U0_m_axi_gmem3_AWLEN;
wire   [2:0] write_weights_U0_m_axi_gmem3_AWSIZE;
wire   [1:0] write_weights_U0_m_axi_gmem3_AWBURST;
wire   [1:0] write_weights_U0_m_axi_gmem3_AWLOCK;
wire   [3:0] write_weights_U0_m_axi_gmem3_AWCACHE;
wire   [2:0] write_weights_U0_m_axi_gmem3_AWPROT;
wire   [3:0] write_weights_U0_m_axi_gmem3_AWQOS;
wire   [3:0] write_weights_U0_m_axi_gmem3_AWREGION;
wire   [0:0] write_weights_U0_m_axi_gmem3_AWUSER;
wire    write_weights_U0_m_axi_gmem3_WVALID;
wire   [511:0] write_weights_U0_m_axi_gmem3_WDATA;
wire   [63:0] write_weights_U0_m_axi_gmem3_WSTRB;
wire    write_weights_U0_m_axi_gmem3_WLAST;
wire   [0:0] write_weights_U0_m_axi_gmem3_WID;
wire   [0:0] write_weights_U0_m_axi_gmem3_WUSER;
wire    write_weights_U0_m_axi_gmem3_ARVALID;
wire   [63:0] write_weights_U0_m_axi_gmem3_ARADDR;
wire   [0:0] write_weights_U0_m_axi_gmem3_ARID;
wire   [31:0] write_weights_U0_m_axi_gmem3_ARLEN;
wire   [2:0] write_weights_U0_m_axi_gmem3_ARSIZE;
wire   [1:0] write_weights_U0_m_axi_gmem3_ARBURST;
wire   [1:0] write_weights_U0_m_axi_gmem3_ARLOCK;
wire   [3:0] write_weights_U0_m_axi_gmem3_ARCACHE;
wire   [2:0] write_weights_U0_m_axi_gmem3_ARPROT;
wire   [3:0] write_weights_U0_m_axi_gmem3_ARQOS;
wire   [3:0] write_weights_U0_m_axi_gmem3_ARREGION;
wire   [0:0] write_weights_U0_m_axi_gmem3_ARUSER;
wire    write_weights_U0_m_axi_gmem3_RREADY;
wire    write_weights_U0_m_axi_gmem3_BREADY;
wire    write_weights_U0_num_verts_read;
wire    write_weights_U0_weights_read;
wire    ap_sync_continue;
wire    num_verts_c_full_n;
wire   [63:0] num_verts_c_dout;
wire    num_verts_c_empty_n;
wire    num_verts_c15_full_n;
wire   [63:0] num_verts_c15_dout;
wire    num_verts_c15_empty_n;
wire    num_edges_c_full_n;
wire   [63:0] num_edges_c_dout;
wire    num_edges_c_empty_n;
wire    vertices_c_full_n;
wire   [63:0] vertices_c_dout;
wire    vertices_c_empty_n;
wire    edges_c_full_n;
wire   [63:0] edges_c_dout;
wire    edges_c_empty_n;
wire    inputs_c_full_n;
wire   [63:0] inputs_c_dout;
wire    inputs_c_empty_n;
wire    outputs_c_full_n;
wire   [63:0] outputs_c_dout;
wire    outputs_c_empty_n;
wire    ie_counts_full_n;
wire   [63:0] ie_counts_dout;
wire    ie_counts_empty_n;
wire    oe_counts_full_n;
wire   [63:0] oe_counts_dout;
wire    oe_counts_empty_n;
wire    in_edges_full_n;
wire   [63:0] in_edges_dout;
wire    in_edges_empty_n;
wire    num_edges_c16_full_n;
wire   [63:0] num_edges_c16_dout;
wire    num_edges_c16_empty_n;
wire    in_weights_full_n;
wire   [63:0] in_weights_dout;
wire    in_weights_empty_n;
wire    weights_full_n;
wire   [63:0] weights_dout;
wire    weights_empty_n;
wire    num_verts_c17_full_n;
wire   [63:0] num_verts_c17_dout;
wire    num_verts_c17_empty_n;
wire    out_weights_full_n;
wire   [63:0] out_weights_dout;
wire    out_weights_empty_n;
wire    num_verts_c18_full_n;
wire   [63:0] num_verts_c18_dout;
wire    num_verts_c18_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_pgrnk_entry3_U0_ap_ready;
wire    ap_sync_pgrnk_entry3_U0_ap_ready;
reg    ap_sync_reg_fetch_verts_U0_ap_ready;
wire    ap_sync_fetch_verts_U0_ap_ready;
reg    ap_sync_reg_fetch_edges_U0_ap_ready;
wire    ap_sync_fetch_edges_U0_ap_ready;
reg    ap_sync_reg_fetch_weights_U0_ap_ready;
wire    ap_sync_fetch_weights_U0_ap_ready;
wire   [0:0] start_for_sum_weights_U0_din;
wire    start_for_sum_weights_U0_full_n;
wire   [0:0] start_for_sum_weights_U0_dout;
wire    start_for_sum_weights_U0_empty_n;
wire   [0:0] start_for_write_weights_U0_din;
wire    start_for_write_weights_U0_full_n;
wire   [0:0] start_for_write_weights_U0_dout;
wire    start_for_write_weights_U0_empty_n;
wire   [0:0] start_for_div_weights_U0_din;
wire    start_for_div_weights_U0_full_n;
wire   [0:0] start_for_div_weights_U0_dout;
wire    start_for_div_weights_U0_empty_n;
wire    fetch_edges_U0_start_full_n;
wire    fetch_edges_U0_start_write;
wire    fetch_weights_U0_start_full_n;
wire    fetch_weights_U0_start_write;
wire    sum_weights_U0_start_full_n;
wire    sum_weights_U0_start_write;
wire    div_weights_U0_start_full_n;
wire    div_weights_U0_start_write;
wire    write_weights_U0_start_full_n;
wire    write_weights_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_pgrnk_entry3_U0_ap_ready = 1'b0;
#0 ap_sync_reg_fetch_verts_U0_ap_ready = 1'b0;
#0 ap_sync_reg_fetch_edges_U0_ap_ready = 1'b0;
#0 ap_sync_reg_fetch_weights_U0_ap_ready = 1'b0;
end

pgrnk_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_verts(num_verts),
    .num_edges(num_edges),
    .vertices(vertices),
    .edges(edges),
    .inputs(inputs),
    .outputs(outputs),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

pgrnk_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 4 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 2 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(fetch_verts_U0_m_axi_gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(fetch_verts_U0_m_axi_gmem0_ARADDR),
    .I_ARID(fetch_verts_U0_m_axi_gmem0_ARID),
    .I_ARLEN(fetch_verts_U0_m_axi_gmem0_ARLEN),
    .I_ARSIZE(fetch_verts_U0_m_axi_gmem0_ARSIZE),
    .I_ARLOCK(fetch_verts_U0_m_axi_gmem0_ARLOCK),
    .I_ARCACHE(fetch_verts_U0_m_axi_gmem0_ARCACHE),
    .I_ARQOS(fetch_verts_U0_m_axi_gmem0_ARQOS),
    .I_ARPROT(fetch_verts_U0_m_axi_gmem0_ARPROT),
    .I_ARUSER(fetch_verts_U0_m_axi_gmem0_ARUSER),
    .I_ARBURST(fetch_verts_U0_m_axi_gmem0_ARBURST),
    .I_ARREGION(fetch_verts_U0_m_axi_gmem0_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(fetch_verts_U0_m_axi_gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(512'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(64'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

pgrnk_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 4 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 2 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(fetch_edges_U0_m_axi_gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(fetch_edges_U0_m_axi_gmem1_ARADDR),
    .I_ARID(fetch_edges_U0_m_axi_gmem1_ARID),
    .I_ARLEN(fetch_edges_U0_m_axi_gmem1_ARLEN),
    .I_ARSIZE(fetch_edges_U0_m_axi_gmem1_ARSIZE),
    .I_ARLOCK(fetch_edges_U0_m_axi_gmem1_ARLOCK),
    .I_ARCACHE(fetch_edges_U0_m_axi_gmem1_ARCACHE),
    .I_ARQOS(fetch_edges_U0_m_axi_gmem1_ARQOS),
    .I_ARPROT(fetch_edges_U0_m_axi_gmem1_ARPROT),
    .I_ARUSER(fetch_edges_U0_m_axi_gmem1_ARUSER),
    .I_ARBURST(fetch_edges_U0_m_axi_gmem1_ARBURST),
    .I_ARREGION(fetch_edges_U0_m_axi_gmem1_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(fetch_edges_U0_m_axi_gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(512'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(64'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

pgrnk_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 64 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 2 ),
    .MAX_WRITE_BURST_LENGTH( 2 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(fetch_weights_U0_m_axi_gmem2_ARVALID),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(fetch_weights_U0_m_axi_gmem2_ARADDR),
    .I_ARID(fetch_weights_U0_m_axi_gmem2_ARID),
    .I_ARLEN(fetch_weights_U0_m_axi_gmem2_ARLEN),
    .I_ARSIZE(fetch_weights_U0_m_axi_gmem2_ARSIZE),
    .I_ARLOCK(fetch_weights_U0_m_axi_gmem2_ARLOCK),
    .I_ARCACHE(fetch_weights_U0_m_axi_gmem2_ARCACHE),
    .I_ARQOS(fetch_weights_U0_m_axi_gmem2_ARQOS),
    .I_ARPROT(fetch_weights_U0_m_axi_gmem2_ARPROT),
    .I_ARUSER(fetch_weights_U0_m_axi_gmem2_ARUSER),
    .I_ARBURST(fetch_weights_U0_m_axi_gmem2_ARBURST),
    .I_ARREGION(fetch_weights_U0_m_axi_gmem2_ARREGION),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(fetch_weights_U0_m_axi_gmem2_RREADY),
    .I_RDATA(gmem2_RDATA),
    .I_RID(gmem2_RID),
    .I_RUSER(gmem2_RUSER),
    .I_RRESP(gmem2_RRESP),
    .I_RLAST(gmem2_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(512'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(64'd0),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem2_BRESP),
    .I_BID(gmem2_BID),
    .I_BUSER(gmem2_BUSER)
);

pgrnk_gmem3_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 4 ),
    .MAX_READ_BURST_LENGTH( 2 ),
    .MAX_WRITE_BURST_LENGTH( 64 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM3_CACHE_VALUE ))
gmem3_m_axi_U(
    .AWVALID(m_axi_gmem3_AWVALID),
    .AWREADY(m_axi_gmem3_AWREADY),
    .AWADDR(m_axi_gmem3_AWADDR),
    .AWID(m_axi_gmem3_AWID),
    .AWLEN(m_axi_gmem3_AWLEN),
    .AWSIZE(m_axi_gmem3_AWSIZE),
    .AWBURST(m_axi_gmem3_AWBURST),
    .AWLOCK(m_axi_gmem3_AWLOCK),
    .AWCACHE(m_axi_gmem3_AWCACHE),
    .AWPROT(m_axi_gmem3_AWPROT),
    .AWQOS(m_axi_gmem3_AWQOS),
    .AWREGION(m_axi_gmem3_AWREGION),
    .AWUSER(m_axi_gmem3_AWUSER),
    .WVALID(m_axi_gmem3_WVALID),
    .WREADY(m_axi_gmem3_WREADY),
    .WDATA(m_axi_gmem3_WDATA),
    .WSTRB(m_axi_gmem3_WSTRB),
    .WLAST(m_axi_gmem3_WLAST),
    .WID(m_axi_gmem3_WID),
    .WUSER(m_axi_gmem3_WUSER),
    .ARVALID(m_axi_gmem3_ARVALID),
    .ARREADY(m_axi_gmem3_ARREADY),
    .ARADDR(m_axi_gmem3_ARADDR),
    .ARID(m_axi_gmem3_ARID),
    .ARLEN(m_axi_gmem3_ARLEN),
    .ARSIZE(m_axi_gmem3_ARSIZE),
    .ARBURST(m_axi_gmem3_ARBURST),
    .ARLOCK(m_axi_gmem3_ARLOCK),
    .ARCACHE(m_axi_gmem3_ARCACHE),
    .ARPROT(m_axi_gmem3_ARPROT),
    .ARQOS(m_axi_gmem3_ARQOS),
    .ARREGION(m_axi_gmem3_ARREGION),
    .ARUSER(m_axi_gmem3_ARUSER),
    .RVALID(m_axi_gmem3_RVALID),
    .RREADY(m_axi_gmem3_RREADY),
    .RDATA(m_axi_gmem3_RDATA),
    .RLAST(m_axi_gmem3_RLAST),
    .RID(m_axi_gmem3_RID),
    .RUSER(m_axi_gmem3_RUSER),
    .RRESP(m_axi_gmem3_RRESP),
    .BVALID(m_axi_gmem3_BVALID),
    .BREADY(m_axi_gmem3_BREADY),
    .BRESP(m_axi_gmem3_BRESP),
    .BID(m_axi_gmem3_BID),
    .BUSER(m_axi_gmem3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem3_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem3_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem3_RDATA),
    .I_RID(gmem3_RID),
    .I_RUSER(gmem3_RUSER),
    .I_RRESP(gmem3_RRESP),
    .I_RLAST(gmem3_RLAST),
    .I_AWVALID(write_weights_U0_m_axi_gmem3_AWVALID),
    .I_AWREADY(gmem3_AWREADY),
    .I_AWADDR(write_weights_U0_m_axi_gmem3_AWADDR),
    .I_AWID(write_weights_U0_m_axi_gmem3_AWID),
    .I_AWLEN(write_weights_U0_m_axi_gmem3_AWLEN),
    .I_AWSIZE(write_weights_U0_m_axi_gmem3_AWSIZE),
    .I_AWLOCK(write_weights_U0_m_axi_gmem3_AWLOCK),
    .I_AWCACHE(write_weights_U0_m_axi_gmem3_AWCACHE),
    .I_AWQOS(write_weights_U0_m_axi_gmem3_AWQOS),
    .I_AWPROT(write_weights_U0_m_axi_gmem3_AWPROT),
    .I_AWUSER(write_weights_U0_m_axi_gmem3_AWUSER),
    .I_AWBURST(write_weights_U0_m_axi_gmem3_AWBURST),
    .I_AWREGION(write_weights_U0_m_axi_gmem3_AWREGION),
    .I_WVALID(write_weights_U0_m_axi_gmem3_WVALID),
    .I_WREADY(gmem3_WREADY),
    .I_WDATA(write_weights_U0_m_axi_gmem3_WDATA),
    .I_WID(write_weights_U0_m_axi_gmem3_WID),
    .I_WUSER(write_weights_U0_m_axi_gmem3_WUSER),
    .I_WLAST(write_weights_U0_m_axi_gmem3_WLAST),
    .I_WSTRB(write_weights_U0_m_axi_gmem3_WSTRB),
    .I_BVALID(gmem3_BVALID),
    .I_BREADY(write_weights_U0_m_axi_gmem3_BREADY),
    .I_BRESP(gmem3_BRESP),
    .I_BID(gmem3_BID),
    .I_BUSER(gmem3_BUSER)
);

pgrnk_pgrnk_entry3 pgrnk_entry3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pgrnk_entry3_U0_ap_start),
    .start_full_n(pgrnk_entry3_U0_start_full_n),
    .ap_done(pgrnk_entry3_U0_ap_done),
    .ap_continue(pgrnk_entry3_U0_ap_continue),
    .ap_idle(pgrnk_entry3_U0_ap_idle),
    .ap_ready(pgrnk_entry3_U0_ap_ready),
    .start_out(pgrnk_entry3_U0_start_out),
    .start_write(pgrnk_entry3_U0_start_write),
    .num_verts(num_verts),
    .num_edges(num_edges),
    .vertices(vertices),
    .edges(edges),
    .inputs(inputs),
    .outputs(outputs),
    .num_verts_out_din(pgrnk_entry3_U0_num_verts_out_din),
    .num_verts_out_full_n(num_verts_c_full_n),
    .num_verts_out_write(pgrnk_entry3_U0_num_verts_out_write),
    .num_verts_out1_din(pgrnk_entry3_U0_num_verts_out1_din),
    .num_verts_out1_full_n(num_verts_c15_full_n),
    .num_verts_out1_write(pgrnk_entry3_U0_num_verts_out1_write),
    .num_edges_out_din(pgrnk_entry3_U0_num_edges_out_din),
    .num_edges_out_full_n(num_edges_c_full_n),
    .num_edges_out_write(pgrnk_entry3_U0_num_edges_out_write),
    .vertices_out_din(pgrnk_entry3_U0_vertices_out_din),
    .vertices_out_full_n(vertices_c_full_n),
    .vertices_out_write(pgrnk_entry3_U0_vertices_out_write),
    .edges_out_din(pgrnk_entry3_U0_edges_out_din),
    .edges_out_full_n(edges_c_full_n),
    .edges_out_write(pgrnk_entry3_U0_edges_out_write),
    .inputs_out_din(pgrnk_entry3_U0_inputs_out_din),
    .inputs_out_full_n(inputs_c_full_n),
    .inputs_out_write(pgrnk_entry3_U0_inputs_out_write),
    .outputs_out_din(pgrnk_entry3_U0_outputs_out_din),
    .outputs_out_full_n(outputs_c_full_n),
    .outputs_out_write(pgrnk_entry3_U0_outputs_out_write)
);

pgrnk_fetch_verts fetch_verts_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fetch_verts_U0_ap_start),
    .start_full_n(start_for_div_weights_U0_full_n),
    .ap_done(fetch_verts_U0_ap_done),
    .ap_continue(fetch_verts_U0_ap_continue),
    .ap_idle(fetch_verts_U0_ap_idle),
    .ap_ready(fetch_verts_U0_ap_ready),
    .start_out(fetch_verts_U0_start_out),
    .start_write(fetch_verts_U0_start_write),
    .m_axi_gmem0_AWVALID(fetch_verts_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(fetch_verts_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(fetch_verts_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(fetch_verts_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(fetch_verts_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(fetch_verts_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(fetch_verts_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(fetch_verts_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(fetch_verts_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(fetch_verts_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(fetch_verts_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(fetch_verts_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(fetch_verts_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(fetch_verts_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(fetch_verts_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(fetch_verts_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(fetch_verts_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(fetch_verts_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(fetch_verts_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(fetch_verts_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(fetch_verts_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(fetch_verts_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(fetch_verts_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(fetch_verts_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(fetch_verts_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(fetch_verts_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(fetch_verts_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(fetch_verts_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(fetch_verts_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(fetch_verts_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(fetch_verts_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(fetch_verts_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .ie_counts_din(fetch_verts_U0_ie_counts_din),
    .ie_counts_full_n(ie_counts_full_n),
    .ie_counts_write(fetch_verts_U0_ie_counts_write),
    .oe_counts_din(fetch_verts_U0_oe_counts_din),
    .oe_counts_full_n(oe_counts_full_n),
    .oe_counts_write(fetch_verts_U0_oe_counts_write),
    .num_verts_dout(num_verts_c_dout),
    .num_verts_empty_n(num_verts_c_empty_n),
    .num_verts_read(fetch_verts_U0_num_verts_read),
    .vertices_dout(vertices_c_dout),
    .vertices_empty_n(vertices_c_empty_n),
    .vertices_read(fetch_verts_U0_vertices_read)
);

pgrnk_fetch_edges fetch_edges_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fetch_edges_U0_ap_start),
    .ap_done(fetch_edges_U0_ap_done),
    .ap_continue(fetch_edges_U0_ap_continue),
    .ap_idle(fetch_edges_U0_ap_idle),
    .ap_ready(fetch_edges_U0_ap_ready),
    .m_axi_gmem1_AWVALID(fetch_edges_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(fetch_edges_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(fetch_edges_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(fetch_edges_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(fetch_edges_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(fetch_edges_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(fetch_edges_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(fetch_edges_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(fetch_edges_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(fetch_edges_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(fetch_edges_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(fetch_edges_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(fetch_edges_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(fetch_edges_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(fetch_edges_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(fetch_edges_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(fetch_edges_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(fetch_edges_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(fetch_edges_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(fetch_edges_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(fetch_edges_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(fetch_edges_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(fetch_edges_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(fetch_edges_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(fetch_edges_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(fetch_edges_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(fetch_edges_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(fetch_edges_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(fetch_edges_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(fetch_edges_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(fetch_edges_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(fetch_edges_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .in_edges_din(fetch_edges_U0_in_edges_din),
    .in_edges_full_n(in_edges_full_n),
    .in_edges_write(fetch_edges_U0_in_edges_write),
    .num_edges_dout(num_edges_c_dout),
    .num_edges_empty_n(num_edges_c_empty_n),
    .num_edges_read(fetch_edges_U0_num_edges_read),
    .edges_dout(edges_c_dout),
    .edges_empty_n(edges_c_empty_n),
    .edges_read(fetch_edges_U0_edges_read),
    .num_edges_out_din(fetch_edges_U0_num_edges_out_din),
    .num_edges_out_full_n(num_edges_c16_full_n),
    .num_edges_out_write(fetch_edges_U0_num_edges_out_write)
);

pgrnk_fetch_weights fetch_weights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fetch_weights_U0_ap_start),
    .ap_done(fetch_weights_U0_ap_done),
    .ap_continue(fetch_weights_U0_ap_continue),
    .ap_idle(fetch_weights_U0_ap_idle),
    .ap_ready(fetch_weights_U0_ap_ready),
    .m_axi_gmem2_AWVALID(fetch_weights_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(1'b0),
    .m_axi_gmem2_AWADDR(fetch_weights_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(fetch_weights_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(fetch_weights_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(fetch_weights_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(fetch_weights_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(fetch_weights_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(fetch_weights_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(fetch_weights_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(fetch_weights_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(fetch_weights_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(fetch_weights_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(fetch_weights_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(1'b0),
    .m_axi_gmem2_WDATA(fetch_weights_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(fetch_weights_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(fetch_weights_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(fetch_weights_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(fetch_weights_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(fetch_weights_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(fetch_weights_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(fetch_weights_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(fetch_weights_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(fetch_weights_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(fetch_weights_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(fetch_weights_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(fetch_weights_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(fetch_weights_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(fetch_weights_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(fetch_weights_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(fetch_weights_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(gmem2_RVALID),
    .m_axi_gmem2_RREADY(fetch_weights_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(gmem2_RDATA),
    .m_axi_gmem2_RLAST(gmem2_RLAST),
    .m_axi_gmem2_RID(gmem2_RID),
    .m_axi_gmem2_RUSER(gmem2_RUSER),
    .m_axi_gmem2_RRESP(gmem2_RRESP),
    .m_axi_gmem2_BVALID(1'b0),
    .m_axi_gmem2_BREADY(fetch_weights_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(2'd0),
    .m_axi_gmem2_BID(1'd0),
    .m_axi_gmem2_BUSER(1'd0),
    .in_edges_dout(in_edges_dout),
    .in_edges_empty_n(in_edges_empty_n),
    .in_edges_read(fetch_weights_U0_in_edges_read),
    .in_weights_din(fetch_weights_U0_in_weights_din),
    .in_weights_full_n(in_weights_full_n),
    .in_weights_write(fetch_weights_U0_in_weights_write),
    .num_weights_dout(num_edges_c16_dout),
    .num_weights_empty_n(num_edges_c16_empty_n),
    .num_weights_read(fetch_weights_U0_num_weights_read),
    .weights_dout(inputs_c_dout),
    .weights_empty_n(inputs_c_empty_n),
    .weights_read(fetch_weights_U0_weights_read)
);

pgrnk_sum_weights sum_weights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sum_weights_U0_ap_start),
    .ap_done(sum_weights_U0_ap_done),
    .ap_continue(sum_weights_U0_ap_continue),
    .ap_idle(sum_weights_U0_ap_idle),
    .ap_ready(sum_weights_U0_ap_ready),
    .ie_counts_dout(ie_counts_dout),
    .ie_counts_empty_n(ie_counts_empty_n),
    .ie_counts_read(sum_weights_U0_ie_counts_read),
    .in_weights_dout(in_weights_dout),
    .in_weights_empty_n(in_weights_empty_n),
    .in_weights_read(sum_weights_U0_in_weights_read),
    .weights_din(sum_weights_U0_weights_din),
    .weights_full_n(weights_full_n),
    .weights_write(sum_weights_U0_weights_write),
    .num_verts_dout(num_verts_c15_dout),
    .num_verts_empty_n(num_verts_c15_empty_n),
    .num_verts_read(sum_weights_U0_num_verts_read),
    .num_verts_out_din(sum_weights_U0_num_verts_out_din),
    .num_verts_out_full_n(num_verts_c17_full_n),
    .num_verts_out_write(sum_weights_U0_num_verts_out_write)
);

pgrnk_div_weights div_weights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(div_weights_U0_ap_start),
    .ap_done(div_weights_U0_ap_done),
    .ap_continue(div_weights_U0_ap_continue),
    .ap_idle(div_weights_U0_ap_idle),
    .ap_ready(div_weights_U0_ap_ready),
    .weights_dout(weights_dout),
    .weights_empty_n(weights_empty_n),
    .weights_read(div_weights_U0_weights_read),
    .oe_counts_dout(oe_counts_dout),
    .oe_counts_empty_n(oe_counts_empty_n),
    .oe_counts_read(div_weights_U0_oe_counts_read),
    .out_weights_din(div_weights_U0_out_weights_din),
    .out_weights_full_n(out_weights_full_n),
    .out_weights_write(div_weights_U0_out_weights_write),
    .num_verts_dout(num_verts_c17_dout),
    .num_verts_empty_n(num_verts_c17_empty_n),
    .num_verts_read(div_weights_U0_num_verts_read),
    .num_verts_out_din(div_weights_U0_num_verts_out_din),
    .num_verts_out_full_n(num_verts_c18_full_n),
    .num_verts_out_write(div_weights_U0_num_verts_out_write)
);

pgrnk_write_weights write_weights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_weights_U0_ap_start),
    .ap_done(write_weights_U0_ap_done),
    .ap_continue(write_weights_U0_ap_continue),
    .ap_idle(write_weights_U0_ap_idle),
    .ap_ready(write_weights_U0_ap_ready),
    .out_weights_dout(out_weights_dout),
    .out_weights_empty_n(out_weights_empty_n),
    .out_weights_read(write_weights_U0_out_weights_read),
    .m_axi_gmem3_AWVALID(write_weights_U0_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(gmem3_AWREADY),
    .m_axi_gmem3_AWADDR(write_weights_U0_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(write_weights_U0_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(write_weights_U0_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(write_weights_U0_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(write_weights_U0_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(write_weights_U0_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(write_weights_U0_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(write_weights_U0_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(write_weights_U0_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(write_weights_U0_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(write_weights_U0_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(write_weights_U0_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(gmem3_WREADY),
    .m_axi_gmem3_WDATA(write_weights_U0_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(write_weights_U0_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(write_weights_U0_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(write_weights_U0_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(write_weights_U0_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(write_weights_U0_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(1'b0),
    .m_axi_gmem3_ARADDR(write_weights_U0_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(write_weights_U0_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(write_weights_U0_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(write_weights_U0_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(write_weights_U0_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(write_weights_U0_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(write_weights_U0_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(write_weights_U0_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(write_weights_U0_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(write_weights_U0_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(write_weights_U0_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(1'b0),
    .m_axi_gmem3_RREADY(write_weights_U0_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(512'd0),
    .m_axi_gmem3_RLAST(1'b0),
    .m_axi_gmem3_RID(1'd0),
    .m_axi_gmem3_RUSER(1'd0),
    .m_axi_gmem3_RRESP(2'd0),
    .m_axi_gmem3_BVALID(gmem3_BVALID),
    .m_axi_gmem3_BREADY(write_weights_U0_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(gmem3_BRESP),
    .m_axi_gmem3_BID(gmem3_BID),
    .m_axi_gmem3_BUSER(gmem3_BUSER),
    .num_verts_dout(num_verts_c18_dout),
    .num_verts_empty_n(num_verts_c18_empty_n),
    .num_verts_read(write_weights_U0_num_verts_read),
    .weights_dout(outputs_c_dout),
    .weights_empty_n(outputs_c_empty_n),
    .weights_read(write_weights_U0_weights_read)
);

pgrnk_fifo_w64_d2_S num_verts_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_num_verts_out_din),
    .if_full_n(num_verts_c_full_n),
    .if_write(pgrnk_entry3_U0_num_verts_out_write),
    .if_dout(num_verts_c_dout),
    .if_empty_n(num_verts_c_empty_n),
    .if_read(fetch_verts_U0_num_verts_read)
);

pgrnk_fifo_w64_d4_S num_verts_c15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_num_verts_out1_din),
    .if_full_n(num_verts_c15_full_n),
    .if_write(pgrnk_entry3_U0_num_verts_out1_write),
    .if_dout(num_verts_c15_dout),
    .if_empty_n(num_verts_c15_empty_n),
    .if_read(sum_weights_U0_num_verts_read)
);

pgrnk_fifo_w64_d2_S num_edges_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_num_edges_out_din),
    .if_full_n(num_edges_c_full_n),
    .if_write(pgrnk_entry3_U0_num_edges_out_write),
    .if_dout(num_edges_c_dout),
    .if_empty_n(num_edges_c_empty_n),
    .if_read(fetch_edges_U0_num_edges_read)
);

pgrnk_fifo_w64_d2_S vertices_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_vertices_out_din),
    .if_full_n(vertices_c_full_n),
    .if_write(pgrnk_entry3_U0_vertices_out_write),
    .if_dout(vertices_c_dout),
    .if_empty_n(vertices_c_empty_n),
    .if_read(fetch_verts_U0_vertices_read)
);

pgrnk_fifo_w64_d2_S edges_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_edges_out_din),
    .if_full_n(edges_c_full_n),
    .if_write(pgrnk_entry3_U0_edges_out_write),
    .if_dout(edges_c_dout),
    .if_empty_n(edges_c_empty_n),
    .if_read(fetch_edges_U0_edges_read)
);

pgrnk_fifo_w64_d3_S inputs_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_inputs_out_din),
    .if_full_n(inputs_c_full_n),
    .if_write(pgrnk_entry3_U0_inputs_out_write),
    .if_dout(inputs_c_dout),
    .if_empty_n(inputs_c_empty_n),
    .if_read(fetch_weights_U0_weights_read)
);

pgrnk_fifo_w64_d6_S outputs_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pgrnk_entry3_U0_outputs_out_din),
    .if_full_n(outputs_c_full_n),
    .if_write(pgrnk_entry3_U0_outputs_out_write),
    .if_dout(outputs_c_dout),
    .if_empty_n(outputs_c_empty_n),
    .if_read(write_weights_U0_weights_read)
);

pgrnk_fifo_w64_d32_A ie_counts_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fetch_verts_U0_ie_counts_din),
    .if_full_n(ie_counts_full_n),
    .if_write(fetch_verts_U0_ie_counts_write),
    .if_dout(ie_counts_dout),
    .if_empty_n(ie_counts_empty_n),
    .if_read(sum_weights_U0_ie_counts_read)
);

pgrnk_fifo_w64_d32_A oe_counts_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fetch_verts_U0_oe_counts_din),
    .if_full_n(oe_counts_full_n),
    .if_write(fetch_verts_U0_oe_counts_write),
    .if_dout(oe_counts_dout),
    .if_empty_n(oe_counts_empty_n),
    .if_read(div_weights_U0_oe_counts_read)
);

pgrnk_fifo_w64_d32_A in_edges_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fetch_edges_U0_in_edges_din),
    .if_full_n(in_edges_full_n),
    .if_write(fetch_edges_U0_in_edges_write),
    .if_dout(in_edges_dout),
    .if_empty_n(in_edges_empty_n),
    .if_read(fetch_weights_U0_in_edges_read)
);

pgrnk_fifo_w64_d2_S num_edges_c16_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fetch_edges_U0_num_edges_out_din),
    .if_full_n(num_edges_c16_full_n),
    .if_write(fetch_edges_U0_num_edges_out_write),
    .if_dout(num_edges_c16_dout),
    .if_empty_n(num_edges_c16_empty_n),
    .if_read(fetch_weights_U0_num_weights_read)
);

pgrnk_fifo_w64_d32_A in_weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fetch_weights_U0_in_weights_din),
    .if_full_n(in_weights_full_n),
    .if_write(fetch_weights_U0_in_weights_write),
    .if_dout(in_weights_dout),
    .if_empty_n(in_weights_empty_n),
    .if_read(sum_weights_U0_in_weights_read)
);

pgrnk_fifo_w64_d32_A weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sum_weights_U0_weights_din),
    .if_full_n(weights_full_n),
    .if_write(sum_weights_U0_weights_write),
    .if_dout(weights_dout),
    .if_empty_n(weights_empty_n),
    .if_read(div_weights_U0_weights_read)
);

pgrnk_fifo_w64_d2_S num_verts_c17_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sum_weights_U0_num_verts_out_din),
    .if_full_n(num_verts_c17_full_n),
    .if_write(sum_weights_U0_num_verts_out_write),
    .if_dout(num_verts_c17_dout),
    .if_empty_n(num_verts_c17_empty_n),
    .if_read(div_weights_U0_num_verts_read)
);

pgrnk_fifo_w64_d32_A out_weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(div_weights_U0_out_weights_din),
    .if_full_n(out_weights_full_n),
    .if_write(div_weights_U0_out_weights_write),
    .if_dout(out_weights_dout),
    .if_empty_n(out_weights_empty_n),
    .if_read(write_weights_U0_out_weights_read)
);

pgrnk_fifo_w64_d2_S num_verts_c18_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(div_weights_U0_num_verts_out_din),
    .if_full_n(num_verts_c18_full_n),
    .if_write(div_weights_U0_num_verts_out_write),
    .if_dout(num_verts_c18_dout),
    .if_empty_n(num_verts_c18_empty_n),
    .if_read(write_weights_U0_num_verts_read)
);

pgrnk_start_for_sum_weights_U0 start_for_sum_weights_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sum_weights_U0_din),
    .if_full_n(start_for_sum_weights_U0_full_n),
    .if_write(pgrnk_entry3_U0_start_write),
    .if_dout(start_for_sum_weights_U0_dout),
    .if_empty_n(start_for_sum_weights_U0_empty_n),
    .if_read(sum_weights_U0_ap_ready)
);

pgrnk_start_for_write_weights_U0 start_for_write_weights_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_weights_U0_din),
    .if_full_n(start_for_write_weights_U0_full_n),
    .if_write(pgrnk_entry3_U0_start_write),
    .if_dout(start_for_write_weights_U0_dout),
    .if_empty_n(start_for_write_weights_U0_empty_n),
    .if_read(write_weights_U0_ap_ready)
);

pgrnk_start_for_div_weights_U0 start_for_div_weights_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_div_weights_U0_din),
    .if_full_n(start_for_div_weights_U0_full_n),
    .if_write(fetch_verts_U0_start_write),
    .if_dout(start_for_div_weights_U0_dout),
    .if_empty_n(start_for_div_weights_U0_empty_n),
    .if_read(div_weights_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_fetch_edges_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_fetch_edges_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_fetch_edges_U0_ap_ready <= ap_sync_fetch_edges_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_fetch_verts_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_fetch_verts_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_fetch_verts_U0_ap_ready <= ap_sync_fetch_verts_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_fetch_weights_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_fetch_weights_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_fetch_weights_U0_ap_ready <= ap_sync_fetch_weights_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_pgrnk_entry3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_pgrnk_entry3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_pgrnk_entry3_U0_ap_ready <= ap_sync_pgrnk_entry3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = write_weights_U0_ap_done;

assign ap_idle = (write_weights_U0_ap_idle & sum_weights_U0_ap_idle & pgrnk_entry3_U0_ap_idle & fetch_weights_U0_ap_idle & fetch_verts_U0_ap_idle & fetch_edges_U0_ap_idle & div_weights_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = write_weights_U0_ap_done;

assign ap_sync_fetch_edges_U0_ap_ready = (fetch_edges_U0_ap_ready | ap_sync_reg_fetch_edges_U0_ap_ready);

assign ap_sync_fetch_verts_U0_ap_ready = (fetch_verts_U0_ap_ready | ap_sync_reg_fetch_verts_U0_ap_ready);

assign ap_sync_fetch_weights_U0_ap_ready = (fetch_weights_U0_ap_ready | ap_sync_reg_fetch_weights_U0_ap_ready);

assign ap_sync_pgrnk_entry3_U0_ap_ready = (pgrnk_entry3_U0_ap_ready | ap_sync_reg_pgrnk_entry3_U0_ap_ready);

assign ap_sync_ready = (ap_sync_pgrnk_entry3_U0_ap_ready & ap_sync_fetch_weights_U0_ap_ready & ap_sync_fetch_verts_U0_ap_ready & ap_sync_fetch_edges_U0_ap_ready);

assign div_weights_U0_ap_continue = 1'b1;

assign div_weights_U0_ap_start = start_for_div_weights_U0_empty_n;

assign div_weights_U0_start_full_n = 1'b1;

assign div_weights_U0_start_write = 1'b0;

assign fetch_edges_U0_ap_continue = 1'b1;

assign fetch_edges_U0_ap_start = ((ap_sync_reg_fetch_edges_U0_ap_ready ^ 1'b1) & ap_start);

assign fetch_edges_U0_start_full_n = 1'b1;

assign fetch_edges_U0_start_write = 1'b0;

assign fetch_verts_U0_ap_continue = 1'b1;

assign fetch_verts_U0_ap_start = ((ap_sync_reg_fetch_verts_U0_ap_ready ^ 1'b1) & ap_start);

assign fetch_weights_U0_ap_continue = 1'b1;

assign fetch_weights_U0_ap_start = ((ap_sync_reg_fetch_weights_U0_ap_ready ^ 1'b1) & ap_start);

assign fetch_weights_U0_start_full_n = 1'b1;

assign fetch_weights_U0_start_write = 1'b0;

assign pgrnk_entry3_U0_ap_continue = 1'b1;

assign pgrnk_entry3_U0_ap_start = ((ap_sync_reg_pgrnk_entry3_U0_ap_ready ^ 1'b1) & ap_start);

assign pgrnk_entry3_U0_start_full_n = (start_for_write_weights_U0_full_n & start_for_sum_weights_U0_full_n);

assign start_for_div_weights_U0_din = 1'b1;

assign start_for_sum_weights_U0_din = 1'b1;

assign start_for_write_weights_U0_din = 1'b1;

assign sum_weights_U0_ap_continue = 1'b1;

assign sum_weights_U0_ap_start = start_for_sum_weights_U0_empty_n;

assign sum_weights_U0_start_full_n = 1'b1;

assign sum_weights_U0_start_write = 1'b0;

assign write_weights_U0_ap_continue = ap_continue;

assign write_weights_U0_ap_start = start_for_write_weights_U0_empty_n;

assign write_weights_U0_start_full_n = 1'b1;

assign write_weights_U0_start_write = 1'b0;

endmodule //pgrnk
